### ISSUE TITLE
PDF Export not working

### ISSUE THREAD

**Issue by r44v** [linuxserver/docker-dillinger#2]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

It appears the pdf functionalities are not working. Initially it appeared to be an permission issue on `/app/dillinger/public` , but after a dirty `chmod 777` the next error was a missing dependency which I fixed with the solution from [here](https://medium.com/@cloverinks/how-to-fix-puppetteer-error-ibx11-xcb-so-1-on-ubuntu-152c336368). But this resulted in missing chromium dependencies, something that should be resolved by the npm install step. (as this also installs puppeteer).

## Expected Behavior
A pdf should be downloading when choosing `Export As > PDF` in the dillinger web-interface

## Current Behavior
An error page occurs with the notice:

    Something wrong with writing the temp MD file.

And the log shows

```
[Error: EACCES: permission denied, open '/app/dillinger/public/files/Filename.md'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/dillinger/public/files/Filename.md'
} 
```

## Steps to Reproduce
1. run docker image
2. Open webinterface
3. Click `EXPORT AS > PDF` (right top)
4. Get unexpected result.

## Environment
**OS:** Windows 10
**CPU architecture:** x86_64
**How docker service was installed:** docker-desktop installer

## Command used to create docker container (run/create/compose/screenshot)
```
docker create \
  --name=dillinger \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Amsterdam \
  -p 9010:8080 \
  --restart unless-stopped \
  linuxserver/dillinger

docker run dillinger
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Dropbox config not found at /app/dillinger/configs/dropbox/dropbox-config.json. Plugin disabled.
Bitbucket config not found at /app/dillinger/configs/bitbucket/bitbucket-config.json. Plugin disabled.
Github config not found at /app/dillinger/configs/github/github-config.json. Plugin disabled.
Medium config not found at /app/dillinger/configs/medium/medium-config.json. Plugin disabled.
Google Drive config not found at /app/dillinger/configs/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /app/dillinger/configs/onedrive/onedrive-config.json. Plugin disabled.
Sponsored config not found at /app/dillinger/configs/sponsored/sponsored-config.json. Plugin disabled.
GoogleAnalytics config not found at /app/dillinger/configs/googleanalytics/googleanalytics-config.json. Plugin disabled.
Sponsored {
  sponsoredConfigFile: '/app/dillinger/configs/sponsored/sponsored-config.json',
  key: null
}
Express server listening on port 8080

http://localhost:8080

::ffff:172.17.0.1 - GET / HTTP/1.1 304 - - 39.407 ms
::ffff:172.17.0.1 - GET /js/main.bundle.js HTTP/1.1 304 - - 1.998 ms
::ffff:172.17.0.1 - GET /img/icons/file.svg HTTP/1.1 304 - - 1.392 ms
::ffff:172.17.0.1 - GET /img/icons/enter-zen.svg HTTP/1.1 304 - - 0.547 ms
::ffff:172.17.0.1 - GET /img/icons/code.svg HTTP/1.1 304 - - 0.648 ms
[Error: EACCES: permission denied, open '/app/dillinger/public/files/Filename.md'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/dillinger/public/files/Filename.md'
}
::ffff:172.17.0.1 - POST /factory/fetch_pdf HTTP/1.1 200 - - 13.194 ms
```

**Comment by tusharsonawanes** [comment]
I deployed this to kubernetes, and I have the same issue. Any help guys ?

**Comment by Tokugero** [comment]
Even without a folder mounted to that directory (/app/dillinger/public/files) I get the same erorr "EACCES". Looks like the folder is owned by root but the node app is running as abc (as expected). The proper fix for this requires an update to those perms on that public folder, as well as installing a bunch of puppeteer reqs that aren't on the official dillinger documentation.

I submitted https://github.com/linuxserver/docker-dillinger/pull/5 for your viewing pleasure.

**Comment by Lordpedal** [comment]
The solution is very simple, there is my **docker-compose.yml**:

```bash
version: "2.1"
services:
  dillinger:
    image: ghcr.io/linuxserver/dillinger
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - '~/docker/dillinger:/config'
    cap_add:
      - SYS_ADMIN
    ports:
      - 8080:8080
    restart: always
```

To fix add this to the docker-compose.yml:

```bash
    cap_add:
      - SYS_ADMIN
```

Or this if you use docker-cli:

```bash
--capt-add=SYS-ADMIN
```
Best regards

**Comment by Tokugero** [comment]
The fix for dependencies had been checked in for some time now, thanks for your config on the sys_admin
